In [10]:
# Question 1
import numpy as np
import torch
import tensorflow as tf

arr_np = np.arange(10)
arr_torch = torch.arange(10)
arr_tf = tf.range(10)

print(arr_np)
print(arr_torch)
print(arr_tf)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [11]:
# Question 2
eye_np = np.eye(3)
eye_torch = torch.eye(3)
eye_tf = tf.eye(3)

print(eye_np)
print(eye_torch)
print(eye_tf)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
# Question 3
np.random.seed(2024)

rand_np = np.random.rand(3, 4)
randint_np = np.random.randint(-10, 10, size=(3, 4))
print('Random 3x4 numpy array in [0, 1):\n', rand_np)
print('\nRandom 3x4 numpy int array in [-10, 10]:\n', randint_np)

Random 3x4 numpy array in [0, 1):
 [[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]

Random 3x4 numpy int array in [-10, 10]:
 [[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]


In [13]:
torch.manual_seed(2024)

rand_torch = torch.rand((3, 4))
randint_torch = torch.randint(-10, 10, (3, 4))
print('Random 3x4 torch tensor in [0, 1)]:\n', rand_torch)
print('\nRandom 3x4 int torch tensor in [-10, 10]:\n', randint_torch)

Random 3x4 torch tensor in [0, 1)]:
 tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])

Random 3x4 int torch tensor in [-10, 10]:
 tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [14]:
tf.random.set_seed(2024)

rand_tf = tf.random.uniform((3, 4))
randint_tf = tf.random.uniform((3, 4), -10, 10, dtype=tf.dtypes.int32)
print('Random 3x4 tf tensor in [0, 1]:\n', rand_tf)
print('Random 3x4 int tf tensor in [-10, 10]:\n', randint_tf)

Random 3x4 tf tensor in [0, 1]:
 tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
Random 3x4 int tf tensor in [-10, 10]:
 tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
