## Stack and Concatenate

In [1]:
import numpy as np
import torch
import tensorflow as tf

2024-04-20 21:59:23.512600: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


#### Question 1

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1, arr2))
arr4 = np.vstack((arr1, arr2))
print('Array 1:\n', arr1)
print('\nArray 2:\n', arr2)
print('\nHorizontally concatenated array:\n', arr3)
print('\nVertically concatenated array:\n', arr4)

Array 1:
 [1 2 3]

Array 2:
 [4 5 6]

Horizontally concatenated array:
 [1 2 3 4 5 6]

Vertically concatenated array:
 [[1 2 3]
 [4 5 6]]


In [5]:
arr1 = torch.tensor([1, 2,3 ])
arr2 = torch.tensor([4, 5, 6])
arr3 = torch.hstack((arr1, arr2))
arr4 = torch.vstack((arr1, arr2))
print('Array 1:\n', arr1)
print('\nArray 2:\n', arr2)
print('\nHorizontally concatenated array:\n', arr3)
print('\nVertically concatenated array:\n', arr4)

Array 1:
 tensor([1, 2, 3])

Array 2:
 tensor([4, 5, 6])

Horizontally concatenated array:
 tensor([1, 2, 3, 4, 5, 6])

Vertically concatenated array:
 tensor([[1, 2, 3],
        [4, 5, 6]])


#### Question 2

In [22]:
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)
arr3 = np.concatenate((arr1, arr2), axis=0)
arr4 = np.concatenate((arr1, arr2), axis=1)
print('Array 1:\n', arr1)
print('\nArray 2:\n', arr2)
print('\nVertically concatenated array (axis=0):\n', arr3)
print('\nHorizontally concatenated array (axis=1):\n', arr4)

Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Vertically concatenated array (axis=0):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizoncally concatenated array (axis=1):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [20]:
arr1 = torch.arange(1, 7).reshape(2, 3)
arr2 = torch.arange(7, 13).reshape(2, 3)
arr3 = torch.cat((arr1, arr2), dim=0)
arr4 = torch.cat((arr1, arr2), dim=1)
print('Array 1:\n', arr1)
print('\nArray 2:\n', arr2)
print('\nVertically concatenated array (axis=0):\n', arr3)
print('\nHorizontally concatenated array (axis=1):\n', arr4)

Array 1:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Array 2:
 tensor([[ 7,  8,  9],
        [10, 11, 12]])

Vertically concatenated array (axis=0):
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Horizoncally concatenated array (axis=1):
 tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


In [25]:
arr1 = tf.constant(tf.range(1, 7), shape=(2, 3))
arr2 = tf.constant(tf.range(7, 13), shape=(2, 3))
arr3 = tf.concat((arr1, arr2), axis=0)
arr4 = tf.concat((arr1, arr2), axis=1)
print('Array 1:\n', arr1)
print('\nArray 2:\n', arr2)
print('\nVertically concatenated array (axis=0):\n', arr3)
print('\nHorizontally concatenated array (axis=1):\n', arr4)

Array 1:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Array 2:
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

Vertically concatenated array (axis=0):
 tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)

Horizontally concatenated array (axis=1):
 tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


## newaxis, expand_dims

In [30]:
arr = torch.tensor([2, 3, 5, 7])
arr1 = arr[None, ...] 
arr2 = arr1[:, None, :, None, None]
print(arr.shape)
print(arr1.shape)
print(arr2.shape)

torch.Size([4])
torch.Size([1, 4])
torch.Size([1, 1, 4, 1, 1])


In [40]:
arr = torch.arange(1, 19).reshape(3, 2, 3)
arr2 = arr.reshape(3, 6)
print(arr)
print(arr.shape)
print('\nAfter reshape:')
print(arr2)
print(arr2.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
torch.Size([3, 2, 3])

After reshape:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]])
torch.Size([3, 6])


## Clip

In [44]:
np.random.seed(2024)
arr = np.random.randint(-10, 10, (3, 3))
print(arr)

arr_clip = np.clip(arr, a_min=3, a_max=8)
print('\nAfter clipping in [3, 8]:', arr_clip)

[[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]

After clipping in [3, 8]: [[3 3 3]
 [3 3 3]
 [3 3 3]]


In [47]:
torch.manual_seed(2024)
arr = torch.randint(-10, 10, size=(3, 4))
print(arr)

arr_clip = torch.clip(arr, min=3, max=8)
print('\nAfter clipping in [3, 8]:\n', arr_clip)

tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])

After clipping in [3, 8]:
 tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 8, 7, 3]])


In [51]:
tf.random.set_seed(2024)
arr = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.int32)
print(arr)

arr_clip = tf.clip_by_value(arr, clip_value_min=3, clip_value_max=8)
print('\nAfter clipping in [3, 8]:\n', arr_clip)

tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)

After clipping in [3, 8]:
 tf.Tensor(
[[3 3 3 3]
 [4 4 3 3]
 [7 3 3 3]], shape=(3, 4), dtype=int32)


In [52]:
arr = torch.randint(-5, 10, size=(4, 3))
arr_clip = torch.clip(arr, min=-2, max=0)
print(arr)
print('\nAfter clipping in [-2, 0]:\n', arr_clip)

tensor([[ 4,  6,  6],
        [ 9,  7,  6],
        [ 0,  8,  1],
        [-3, -3,  6]])

After clipping in [-2, 0]:
 tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [-2, -2,  0]])


## Indexing

In [55]:
arr = torch.arange(1, 19).reshape(3, 2, 3)
arr.shape

torch.Size([3, 2, 3])

In [58]:
arr[0:1, 0:1, 0:1]

tensor([[[1]]])

In [59]:
arr[0, 0:1, 0:1]

tensor([[1]])

In [62]:
arr = [[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]]

torch_arr = torch.tensor(arr)
print(torch_arr)
print('\nRow 2 without reducing dimension:\n', torch_arr[1:2, :])
print('\nRow 2 with reducing dimension:\n', torch_arr[1, :])
print('\nCol 1 without reducing dimension:\n', torch_arr[:, 0:1])
print('\nCol 1 with reducing dimension:\n', torch_arr[:, 0])

tensor([[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]])

Row 2 without reducing dimension:
 tensor([[0, 1, 0]])

Row 2 with reducing dimension:
 tensor([0, 1, 0])

Col 1 without reducing dimension:
 tensor([[1],
        [0],
        [1]])

Col 1 with reducing dimension:
 tensor([1, 0, 1])


In [63]:
arr = torch.randint(-10, 10, size=(3, 3))
filtered_arr = arr[arr > 0]
print(arr)
print('\nAfter filtered:\n', filtered_arr)

tensor([[ 2,  0,  1],
        [-5,  8, -3],
        [-8, -3, -1]])

After filtered:
 tensor([2, 1, 8])


## Matrix operations 

In [66]:
torch.manual_seed(2024)
arr1 = torch.randint(-10, 10, size=(3, 3))
arr2 = torch.randint(-10, 10, size=(3, 3))
res = torch.matmul(arr1, arr2)
print(arr1)
print(arr2)
print('\nMatrix multiplication result:\n', res)

tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
tensor([[  9,   7,  -6],
        [  1,   8,   0],
        [ -2,  -9, -10]])

Matrix multiplication result:
 tensor([[ 30,  68,  48],
        [-77, -36, 160],
        [ -5, -19, -30]])
