In [43]:
import numpy as np
import torch
import tensorflow as tf

## Question 1 

In [44]:
np.random.seed(2024)
torch.manual_seed(2024)
tf.random.set_seed(2024)

sz = (3, 4)

In [45]:
np_arr1 = np.random.randint(-10, 10, size=sz)
np_arr2 = np.random.randint(-10, 10, size=sz)
np_transpose = np_arr2.T

res = np.dot(np_arr1, np_transpose)
# res = np.arr1 @ np_transpose

print(f'First numpy array:\n{np_arr1}')
print(f'Second numpy array:\n{np_arr2}')
print(f'Transposed second numpy array:\n{np_transpose}')
print(f'Matrix multiplication:\n{res}')

First numpy array:
[[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
Second numpy array:
[[ 5  0  4  5]
 [ 1 -3  8 -1]
 [-4  0 -9 -5]]
Transposed second numpy array:
[[ 5  1 -4]
 [ 0 -3  0]
 [ 4  8 -9]
 [ 5 -1 -5]]
Matrix multiplication:
[[-80 -46 128]
 [-33 -30  67]
 [-25 -25  42]]


In [46]:
torch_tensor1 = torch.randint(-10, 10, size=sz)
torch_tensor2 = torch.randint(-10, 10, size=sz)
torch_transpose = torch_tensor2.T

res = torch.matmul(torch_tensor1, torch_transpose)

print(f'First torch tensor:\n{torch_tensor1}')
print(f'Second torch tensor:\n{torch_tensor2}')
print(f'Transposed second torch tensor:\n{torch_transpose}')
print(f'Matrix multiplication:\n{res}')

First torch tensor:
tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
Second torch tensor:
tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
Transposed second torch tensor:
tensor([[  1,  -9,  -3],
        [  8, -10,  -7],
        [  0,  -9,  -4],
        [ -2,   0,   8]])
Matrix multiplication:
tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]])


In [47]:
tf_tensor1 = tf.random.uniform(shape=sz, minval=-10, maxval=10, dtype=tf.int32)
tf_tensor2 = tf.random.uniform(shape=sz, minval=-10, maxval=10, dtype=tf.int32)
tf_transpose = tf.transpose(tf_tensor2)

res = tf.matmul(tf_tensor1, tf_transpose)

print(f'First tf tensor:\n{tf_tensor1}')
print(f'Second pytorch tensor:\n{tf_tensor2}')
print(f'Transposed second pytorch tensor:\n{tf_transpose}')
print(f'Matrix multiplication:\n{res}')


First tf tensor:
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]]
Second pytorch tensor:
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]]
Transposed second pytorch tensor:
[[-3  2  4]
 [-7 -5 -3]
 [ 9 -3 -3]
 [ 3 -5  5]]
Matrix multiplication:
[[  26    8  -28]
 [-112    0   46]
 [ -25   28   -6]]


## Question 2

In [48]:
np_arr = np.random.randint(-10, 10, size=(3, 3))

total_sum = np.sum(np_arr)
col_sum = np.sum(np_arr, axis=0) # sum of each column
row_sum = np.sum(np_arr, axis=1) # sum of each row

print(f'Numpy array: \n{np_arr}')
print(f'Total sum: {total_sum}')
print(f'Sum of each column: {col_sum}')
print(f'Sum of each row: {row_sum}')

Numpy array: 
[[ 9 -6 -2]
 [ 8 -9  0]
 [-3  6 -2]]
Total sum: 1
Sum of each column: [14 -9 -4]
Sum of each row: [ 1 -1  1]


In [49]:
torch_tensor = torch.randint(-10, 10, size=(3, 3))

total_sum = torch.sum(torch_tensor)
col_sum = torch.sum(torch_tensor, axis=0)
row_sum = torch.sum(torch_tensor, axis=1)

print(f'Torch tensor:\n{torch_tensor}')
print(f'Total sum: {total_sum}')
print(f'Sum of each column: {col_sum}')
print(f'Sum of each row: {row_sum}')

Torch tensor:
tensor([[ 9,  1,  1],
        [-6, -3,  1],
        [ 0,  8,  1]])
Total sum: 12
Sum of each column: tensor([3, 6, 3])
Sum of each row: tensor([11, -8,  9])


In [51]:
tf_tensor = tf.random.uniform(shape=(3, 3), minval=-10, maxval=10, dtype=tf.int32)

total_sum = tf.reduce_sum(tf_tensor)
col_sum = tf.reduce_sum(tf_tensor, axis=0)
row_sum = tf.reduce_sum(tf_tensor, axis=1)

print(f'Tf tensor:\n{tf_tensor}')
print(f'Total sum: {total_sum}')
print(f'Sum of each column: {col_sum}')
print(f'Sum of each row: {row_sum}')


Tf tensor:
[[-4  5  5]
 [-9  7 -7]
 [-2 -4  1]]
Total sum: -8
Sum of each column: [-15   8  -1]
Sum of each row: [ 6 -9 -5]
